/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CalendarDateFilter
import org.openapitools.client.models.DateEnum

class CalendarDateFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarDateFilter
        //val modelInstance = CalendarDateFilter()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``operator`` - Operators for calendar date filters.
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
