/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CampaignMessagePartialUpdateQueryResourceObjectAttributes
import org.openapitools.client.models.CampaignMessageCreateQueryResourceObjectAttributesContent
import org.openapitools.client.models.RenderOptionsSubObject

class CampaignMessagePartialUpdateQueryResourceObjectAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CampaignMessagePartialUpdateQueryResourceObjectAttributes
        //val modelInstance = CampaignMessagePartialUpdateQueryResourceObjectAttributes()

        // to test the property `label` - The label or name on the message
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `renderOptions`
        should("test renderOptions") {
            // uncomment below to test the property
            //modelInstance.renderOptions shouldBe ("TODO")
        }

    }
}
