/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CatalogCategoryDeleteJobCreateQueryResourceObjectAttributes
import org.openapitools.client.models.CatalogCategoryDeleteJobCreateQueryResourceObjectAttributesCategories

class CatalogCategoryDeleteJobCreateQueryResourceObjectAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogCategoryDeleteJobCreateQueryResourceObjectAttributes
        //val modelInstance = CatalogCategoryDeleteJobCreateQueryResourceObjectAttributes()

        // to test the property `categories`
        should("test categories") {
            // uncomment below to test the property
            //modelInstance.categories shouldBe ("TODO")
        }

    }
}
