/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CatalogVariantUpdateJobCreateQueryResourceObject
import org.openapitools.client.models.CatalogVariantBulkUpdateJobEnum
import org.openapitools.client.models.CatalogVariantUpdateJobCreateQueryResourceObjectAttributes

class CatalogVariantUpdateJobCreateQueryResourceObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogVariantUpdateJobCreateQueryResourceObject
        //val modelInstance = CatalogVariantUpdateJobCreateQueryResourceObject()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

    }
}
