/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CheckoutMethodFilter
import org.openapitools.client.models.CheckoutEnum
import org.openapitools.client.models.MethodEnum

class CheckoutMethodFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutMethodFilter
        //val modelInstance = CheckoutMethodFilter()

        // to test the property ``field``
        should("test `field`") {
            // uncomment below to test the property
            //modelInstance.`field` shouldBe ("TODO")
        }

        // to test the property `method`
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

    }
}
