/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ConstantContactIntegrationMethodFilter
import org.openapitools.client.models.ConstantContactIntegrationFilter
import org.openapitools.client.models.IntegrationEnum
import org.openapitools.client.models.MethodEnum

class ConstantContactIntegrationMethodFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConstantContactIntegrationMethodFilter
        //val modelInstance = ConstantContactIntegrationMethodFilter()

        // to test the property ``field``
        should("test `field`") {
            // uncomment below to test the property
            //modelInstance.`field` shouldBe ("TODO")
        }

        // to test the property `method`
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

    }
}
