/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CouponCodeCreateQueryResourceObjectAttributes

class CouponCodeCreateQueryResourceObjectAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CouponCodeCreateQueryResourceObjectAttributes
        //val modelInstance = CouponCodeCreateQueryResourceObjectAttributes()

        // to test the property `uniqueCode` - This is a unique string that will be or is assigned to each customer/profile and is associated with a coupon.
        should("test uniqueCode") {
            // uncomment below to test the property
            //modelInstance.uniqueCode shouldBe ("TODO")
        }

        // to test the property `expiresAt` - The datetime when this coupon code will expire. If not specified or set to null, it will be automatically set to 1 year.
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
