/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ErrorSource

class ErrorSourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorSource
        //val modelInstance = ErrorSource()

        // to test the property `pointer` - A pointer to the source of the error in the request payload.
        should("test pointer") {
            // uncomment below to test the property
            //modelInstance.pointer shouldBe ("TODO")
        }

    }
}
