/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCatalogItemCategoryListResponseCollectionDataInner
import org.openapitools.client.models.CatalogCategoryEnum

class GetCatalogItemCategoryListResponseCollectionDataInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCatalogItemCategoryListResponseCollectionDataInner
        //val modelInstance = GetCatalogItemCategoryListResponseCollectionDataInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id` - A list of catalog category IDs representing the categories the item is in
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
