/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCatalogCategoryDeleteJobResponseCollectionDataInner
import org.openapitools.client.models.CatalogCategoryBulkDeleteJobEnum
import org.openapitools.client.models.CouponCodeCreateJobResponseObjectResourceAttributes
import org.openapitools.client.models.GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships
import org.openapitools.client.models.ObjectLinks

class GetCatalogCategoryDeleteJobResponseCollectionDataInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCatalogCategoryDeleteJobResponseCollectionDataInner
        //val modelInstance = GetCatalogCategoryDeleteJobResponseCollectionDataInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id` - Unique identifier for retrieving the job. Generated by Klaviyo.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `relationships`
        should("test relationships") {
            // uncomment below to test the property
            //modelInstance.relationships shouldBe ("TODO")
        }

    }
}
