/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListListResponseObjectResourceAttributes

class ListListResponseObjectResourceAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListListResponseObjectResourceAttributes
        //val modelInstance = ListListResponseObjectResourceAttributes()

        // to test the property `name` - A helpful name to label the list
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `created` - Date and time when the list was created, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

        // to test the property `updated` - Date and time when the list was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

        // to test the property `optInProcess` - The opt-in process for this list.  Could be either 'single_opt_in' or 'double_opt_in'.
        should("test optInProcess") {
            // uncomment below to test the property
            //modelInstance.optInProcess shouldBe ("TODO")
        }

    }
}
