/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NoEmailMarketing
import org.openapitools.client.models.AnyEnum
import org.openapitools.client.models.NoEmailMarketingFiltersInner

class NoEmailMarketingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NoEmailMarketing
        //val modelInstance = NoEmailMarketing()

        // to test the property `subscription`
        should("test subscription") {
            // uncomment below to test the property
            //modelInstance.subscription shouldBe ("TODO")
        }

        // to test the property `filters`
        should("test filters") {
            // uncomment below to test the property
            //modelInstance.filters shouldBe ("TODO")
        }

    }
}
