/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NoSMSMarketing
import org.openapitools.client.models.AnyEnum

class NoSMSMarketingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NoSMSMarketing
        //val modelInstance = NoSMSMarketing()

        // to test the property `subscription`
        should("test subscription") {
            // uncomment below to test the property
            //modelInstance.subscription shouldBe ("TODO")
        }

    }
}
