/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProfilePredictiveAnalyticsNumericCondition
import org.openapitools.client.models.NumericOperatorFilter
import org.openapitools.client.models.ProfilePredictiveAnalyticsEnum

class ProfilePredictiveAnalyticsNumericConditionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProfilePredictiveAnalyticsNumericCondition
        //val modelInstance = ProfilePredictiveAnalyticsNumericCondition()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `dimension` - Dimensions for numeric profile predictive analytics conditions.
        should("test dimension") {
            // uncomment below to test the property
            //modelInstance.dimension shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

    }
}
