/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProfileLocation
import org.openapitools.client.models.ProfileLocationLatitude
import org.openapitools.client.models.ProfileLocationLongitude

class ProfileLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProfileLocation
        //val modelInstance = ProfileLocation()

        // to test the property `address1` - First line of street address
        should("test address1") {
            // uncomment below to test the property
            //modelInstance.address1 shouldBe ("TODO")
        }

        // to test the property `address2` - Second line of street address
        should("test address2") {
            // uncomment below to test the property
            //modelInstance.address2 shouldBe ("TODO")
        }

        // to test the property `city` - City name
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `country` - Country name
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `region` - Region within a country, such as state or province
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `zip` - Zip code
        should("test zip") {
            // uncomment below to test the property
            //modelInstance.zip shouldBe ("TODO")
        }

        // to test the property `timezone` - Time zone name. We recommend using time zones from the IANA Time Zone Database.
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `ip` - IP Address
        should("test ip") {
            // uncomment below to test the property
            //modelInstance.ip shouldBe ("TODO")
        }

    }
}
