/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PushTokenCreateQueryResourceObjectAttributesProfile
import org.openapitools.client.models.PushProfileUpsertQueryResourceObject

class PushTokenCreateQueryResourceObjectAttributesProfileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PushTokenCreateQueryResourceObjectAttributesProfile
        //val modelInstance = PushTokenCreateQueryResourceObjectAttributesProfile()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

    }
}
