/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SegmentCreateQueryResourceObjectAttributes
import org.openapitools.client.models.SegmentDefinition

class SegmentCreateQueryResourceObjectAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SegmentCreateQueryResourceObjectAttributes
        //val modelInstance = SegmentCreateQueryResourceObjectAttributes()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `definition`
        should("test definition") {
            // uncomment below to test the property
            //modelInstance.definition shouldBe ("TODO")
        }

        // to test the property `isStarred`
        should("test isStarred") {
            // uncomment below to test the property
            //modelInstance.isStarred shouldBe ("TODO")
        }

    }
}
