/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SuppressionCreateJobCreateQueryResourceObjectRelationshipsSegmentData
import org.openapitools.client.models.SegmentEnum

class SuppressionCreateJobCreateQueryResourceObjectRelationshipsSegmentDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionCreateJobCreateQueryResourceObjectRelationshipsSegmentData
        //val modelInstance = SuppressionCreateJobCreateQueryResourceObjectRelationshipsSegmentData()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id` - Suppress all profiles in this segment
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
