/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TemplateCreateQueryResourceObject
import org.openapitools.client.models.TemplateCreateQueryResourceObjectAttributes
import org.openapitools.client.models.TemplateEnum

class TemplateCreateQueryResourceObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TemplateCreateQueryResourceObject
        //val modelInstance = TemplateCreateQueryResourceObject()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

    }
}
