/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ThrottledScheduleOptions

class ThrottledScheduleOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ThrottledScheduleOptions
        //val modelInstance = ThrottledScheduleOptions()

        // to test the property `datetime` - The time to send at
        should("test datetime") {
            // uncomment below to test the property
            //modelInstance.datetime shouldBe ("TODO")
        }

        // to test the property `throttlePercentage` - The percentage of recipients per hour to send to. Allowed values: [10, 11, 13, 14, 17, 20, 25, 33, 50]
        should("test throttlePercentage") {
            // uncomment below to test the property
            //modelInstance.throttlePercentage shouldBe ("TODO")
        }

    }
}
