/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValuesData

class ValuesDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValuesData
        //val modelInstance = ValuesData()

        // to test the property `groupings` - Applied groupings and the values for this object
        should("test groupings") {
            // uncomment below to test the property
            //modelInstance.groupings shouldBe ("TODO")
        }

        // to test the property `statistics` - Requested statistics and their values results
        should("test statistics") {
            // uncomment below to test the property
            //modelInstance.statistics shouldBe ("TODO")
        }

    }
}
