/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.EventsApi
import org.openapitools.client.models.EventCreateQueryV2
import org.openapitools.client.models.EventsBulkCreateJob
import org.openapitools.client.models.GetAccounts4XXResponse
import org.openapitools.client.models.GetEventMetricsRelationshipListResponse
import org.openapitools.client.models.GetEventProfilesRelationshipListResponse
import org.openapitools.client.models.GetEventResponseCollectionCompoundDocument
import org.openapitools.client.models.GetEventResponseCompoundDocument
import org.openapitools.client.models.GetMetricResponseCollection
import org.openapitools.client.models.GetProfileResponseCollection

class EventsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventsApi
        //val apiInstance = EventsApi()

        // to test bulkCreateEvents
        should("test bulkCreateEvents") {
            // uncomment below to test bulkCreateEvents
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val eventsBulkCreateJob : EventsBulkCreateJob =  // EventsBulkCreateJob | 
            //apiInstance.bulkCreateEvents(revision, eventsBulkCreateJob)
        }

        // to test createEvent
        should("test createEvent") {
            // uncomment below to test createEvent
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val eventCreateQueryV2 : EventCreateQueryV2 =  // EventCreateQueryV2 | 
            //apiInstance.createEvent(revision, eventCreateQueryV2)
        }

        // to test getEvent
        should("test getEvent") {
            // uncomment below to test getEvent
            //val id : kotlin.String = id_example // kotlin.String | ID of the event
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val fieldsEvent : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val fieldsMetric : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val fieldsProfile : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#relationships
            //val result : GetEventResponseCompoundDocument = apiInstance.getEvent(id, revision, fieldsEvent, fieldsMetric, fieldsProfile, include)
            //result shouldBe ("TODO")
        }

        // to test getEventMetric
        should("test getEventMetric") {
            // uncomment below to test getEventMetric
            //val id : kotlin.String = id_example // kotlin.String | 
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val fieldsMetric : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val result : GetMetricResponseCollection = apiInstance.getEventMetric(id, revision, fieldsMetric)
            //result shouldBe ("TODO")
        }

        // to test getEventProfile
        should("test getEventProfile") {
            // uncomment below to test getEventProfile
            //val id : kotlin.String = id_example // kotlin.String | 
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val additionalFieldsProfile : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
            //val fieldsProfile : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val result : GetProfileResponseCollection = apiInstance.getEventProfile(id, revision, additionalFieldsProfile, fieldsProfile)
            //result shouldBe ("TODO")
        }

        // to test getEventRelationshipsMetric
        should("test getEventRelationshipsMetric") {
            // uncomment below to test getEventRelationshipsMetric
            //val id : kotlin.String = id_example // kotlin.String | 
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val result : GetEventMetricsRelationshipListResponse = apiInstance.getEventRelationshipsMetric(id, revision)
            //result shouldBe ("TODO")
        }

        // to test getEventRelationshipsProfile
        should("test getEventRelationshipsProfile") {
            // uncomment below to test getEventRelationshipsProfile
            //val id : kotlin.String = id_example // kotlin.String | 
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val result : GetEventProfilesRelationshipListResponse = apiInstance.getEventRelationshipsProfile(id, revision)
            //result shouldBe ("TODO")
        }

        // to test getEvents
        should("test getEvents") {
            // uncomment below to test getEvents
            //val revision : kotlin.String = revision_example // kotlin.String | API endpoint revision (format: YYYY-MM-DD[.suffix])
            //val fieldsEvent : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val fieldsMetric : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val fieldsProfile : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sparse-fieldsets
            //val filter : kotlin.String = filter_example // kotlin.String | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#filtering<br>Allowed field(s)/operator(s):<br>`metric_id`: `equals`<br>`profile_id`: `equals`<br>`profile`: `has`<br>`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`<br>`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
            //val include : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#relationships
            //val pageCursor : kotlin.String = pageCursor_example // kotlin.String | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#pagination
            //val sort : kotlin.String = sort_example // kotlin.String | For more information please visit https://developers.klaviyo.com/en/v2024-07-15/reference/api-overview#sorting
            //val result : GetEventResponseCollectionCompoundDocument = apiInstance.getEvents(revision, fieldsEvent, fieldsMetric, fieldsProfile, filter, include, pageCursor, sort)
            //result shouldBe ("TODO")
        }

    }
}
