/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContactInformation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param testAccount Indicates if the account is a test account. Test accounts are not a separate testing engineering environment. Test accounts use the same production environment as normal Klaviyo accounts. This feature is primarily UI based to reduce human errors
 * @param contactInformation 
 * @param industry The kind of business and/or types of goods that the business sells. This is leveraged in Klaviyo analytics and guidance.
 * @param timezone The account's timezone is used when displaying dates and times. This is an IANA timezone. See [the full list here ](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
 * @param preferredCurrency The preferred currency for the account. This is the currency used for currency-based metrics in dashboards, analytics, coupons, and templates.
 * @param publicApiKey The Public API Key can be used for client-side API calls. [More info here](https://developers.klaviyo.com/en/docs/retrieve_api_credentials).
 * @param locale The account's locale is used to determine the region and language for the account.
 */


data class AccountResponseObjectResourceAttributes (

    /* Indicates if the account is a test account. Test accounts are not a separate testing engineering environment. Test accounts use the same production environment as normal Klaviyo accounts. This feature is primarily UI based to reduce human errors */
    @Json(name = "test_account")
    val testAccount: kotlin.Boolean,

    @Json(name = "contact_information")
    val contactInformation: ContactInformation,

    /* The kind of business and/or types of goods that the business sells. This is leveraged in Klaviyo analytics and guidance. */
    @Json(name = "industry")
    val industry: kotlin.String,

    /* The account's timezone is used when displaying dates and times. This is an IANA timezone. See [the full list here ](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). */
    @Json(name = "timezone")
    val timezone: kotlin.String,

    /* The preferred currency for the account. This is the currency used for currency-based metrics in dashboards, analytics, coupons, and templates. */
    @Json(name = "preferred_currency")
    val preferredCurrency: kotlin.String,

    /* The Public API Key can be used for client-side API calls. [More info here](https://developers.klaviyo.com/en/docs/retrieve_api_credentials). */
    @Json(name = "public_api_key")
    val publicApiKey: kotlin.String,

    /* The account's locale is used to determine the region and language for the account. */
    @Json(name = "locale")
    val locale: kotlin.String

) {


}

