/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DateEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param `operator` Operators for alltime date filters.
 */


data class AlltimeDateFilter (

    @Json(name = "type")
    val type: DateEnum,

    /* Operators for alltime date filters. */
    @Json(name = "operator")
    val `operator`: AlltimeDateFilter.`Operator`

) {

    /**
     * Operators for alltime date filters.
     *
     * Values: alltime
     */
    @JsonClass(generateAdapter = false)
    enum class `Operator`(val value: kotlin.String) {
        @Json(name = "alltime") alltime("alltime");
    }

}

