/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param included A list of included audiences
 * @param excluded An optional list of excluded audiences
 */


data class AudiencesSubObject (

    /* A list of included audiences */
    @Json(name = "included")
    val included: kotlin.collections.List<kotlin.String>? = null,

    /* An optional list of excluded audiences */
    @Json(name = "excluded")
    val excluded: kotlin.collections.List<kotlin.String>? = null

) {


}

