/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AudiencesSubObject
import org.openapitools.client.models.CampaignResponseObjectResourceAttributesSendOptions
import org.openapitools.client.models.CampaignResponseObjectResourceAttributesTrackingOptions
import org.openapitools.client.models.SendStrategySubObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The campaign name
 * @param status The current status of the campaign
 * @param archived Whether the campaign has been archived or not
 * @param audiences 
 * @param sendOptions 
 * @param trackingOptions 
 * @param sendStrategy 
 * @param createdAt The datetime when the campaign was created
 * @param updatedAt The datetime when the campaign was last updated by a user or the system
 * @param scheduledAt The datetime when the campaign was scheduled for future sending
 * @param sendTime The datetime when the campaign will be / was sent or None if not yet scheduled by a send_job.
 */


data class CampaignResponseObjectResourceAttributes (

    /* The campaign name */
    @Json(name = "name")
    val name: kotlin.String,

    /* The current status of the campaign */
    @Json(name = "status")
    val status: kotlin.String,

    /* Whether the campaign has been archived or not */
    @Json(name = "archived")
    val archived: kotlin.Boolean,

    @Json(name = "audiences")
    val audiences: AudiencesSubObject,

    @Json(name = "send_options")
    val sendOptions: CampaignResponseObjectResourceAttributesSendOptions,

    @Json(name = "tracking_options")
    val trackingOptions: CampaignResponseObjectResourceAttributesTrackingOptions,

    @Json(name = "send_strategy")
    val sendStrategy: SendStrategySubObject,

    /* The datetime when the campaign was created */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The datetime when the campaign was last updated by a user or the system */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* The datetime when the campaign was scheduled for future sending */
    @Json(name = "scheduled_at")
    val scheduledAt: java.time.OffsetDateTime? = null,

    /* The datetime when the campaign will be / was sent or None if not yet scheduled by a send_job. */
    @Json(name = "send_time")
    val sendTime: java.time.OffsetDateTime? = null

) {


}

