/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CampaignRecipientEstimationEnum
import org.openapitools.client.models.CampaignRecipientEstimationResponseObjectResourceAttributes
import org.openapitools.client.models.ObjectLinks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param id The ID of the campaign for which to get the estimated number of recipients
 * @param attributes 
 * @param links 
 */


data class CampaignRecipientEstimationResponseObjectResource (

    @Json(name = "type")
    val type: CampaignRecipientEstimationEnum,

    /* The ID of the campaign for which to get the estimated number of recipients */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "attributes")
    val attributes: CampaignRecipientEstimationResponseObjectResourceAttributes,

    @Json(name = "links")
    val links: ObjectLinks

) {


}

