/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param externalId The ID of the catalog category in an external system.
 * @param name The name of the catalog category.
 * @param updated Date and time when the catalog category was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
 */


data class CatalogCategoryResponseObjectResourceAttributes (

    /* The ID of the catalog category in an external system. */
    @Json(name = "external_id")
    val externalId: kotlin.String? = null,

    /* The name of the catalog category. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Date and time when the catalog category was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm). */
    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null

) {


}

