/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CatalogVariantCreateQueryResourceObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Array of catalog variants to create.
 *
 * @param `data` 
 */


data class CatalogVariantCreateJobCreateQueryResourceObjectAttributesVariants (

    @Json(name = "data")
    val `data`: kotlin.collections.List<CatalogVariantCreateQueryResourceObject>

) {


}

