/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CouponCodeCreateQueryResourceObjectRelationshipsCoupon

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param coupon 
 */


data class CouponCodeCreateQueryResourceObjectRelationships (

    @Json(name = "coupon")
    val coupon: CouponCodeCreateQueryResourceObjectRelationshipsCoupon? = null

) {


}

