/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BooleanFilter
import org.openapitools.client.models.IsDoubleOptInEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `field` 
 * @param filter 
 */


data class DoubleOptinFilter (

    @Json(name = "field")
    val `field`: IsDoubleOptInEnum,

    @Json(name = "filter")
    val filter: BooleanFilter

) {


}

