/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reason The reason the profile was suppressed.
 * @param timestamp The timestamp when the profile was suppressed, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
 */


data class EmailMarketingSuppression (

    /* The reason the profile was suppressed. */
    @Json(name = "reason")
    val reason: EmailMarketingSuppression.Reason,

    /* The timestamp when the profile was suppressed, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm). */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime

) {

    /**
     * The reason the profile was suppressed.
     *
     * Values: HARD_BOUNCE,INVALID_EMAIL,SPAM_COMPLAINT,UNSUBSCRIBE,USER_SUPPRESSED
     */
    @JsonClass(generateAdapter = false)
    enum class Reason(val value: kotlin.String) {
        @Json(name = "HARD_BOUNCE") HARD_BOUNCE("HARD_BOUNCE"),
        @Json(name = "INVALID_EMAIL") INVALID_EMAIL("INVALID_EMAIL"),
        @Json(name = "SPAM_COMPLAINT") SPAM_COMPLAINT("SPAM_COMPLAINT"),
        @Json(name = "UNSUBSCRIBE") UNSUBSCRIBE("UNSUBSCRIBE"),
        @Json(name = "USER_SUPPRESSED") USER_SUPPRESSED("USER_SUPPRESSED");
    }

}

