/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UtmParamInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param addUtm 
 * @param utmParams 
 * @param isTrackingOpens 
 * @param isTrackingClicks 
 */


data class EmailTrackingOptions (

    @Json(name = "add_utm")
    val addUtm: kotlin.Boolean,

    @Json(name = "utm_params")
    val utmParams: kotlin.collections.List<UtmParamInfo>,

    @Json(name = "is_tracking_opens")
    val isTrackingOpens: kotlin.Boolean,

    @Json(name = "is_tracking_clicks")
    val isTrackingClicks: kotlin.Boolean

) {


}

