/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param status 
 * @param archived 
 * @param created 
 * @param updated 
 * @param triggerType Corresponds to the object which triggered the flow.
 */


data class FlowResponseObjectResourceAttributes (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "archived")
    val archived: kotlin.Boolean? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null,

    /* Corresponds to the object which triggered the flow. */
    @Json(name = "trigger_type")
    val triggerType: FlowResponseObjectResourceAttributes.TriggerType? = null

) {

    /**
     * Corresponds to the object which triggered the flow.
     *
     * Values: Added_to_List,Date_Based,Low_Inventory,Metric,Price_Drop,Unconfigured
     */
    @JsonClass(generateAdapter = false)
    enum class TriggerType(val value: kotlin.String) {
        @Json(name = "Added to List") Added_to_List("Added to List"),
        @Json(name = "Date Based") Date_Based("Date Based"),
        @Json(name = "Low Inventory") Low_Inventory("Low Inventory"),
        @Json(name = "Metric") Metric("Metric"),
        @Json(name = "Price Drop") Price_Drop("Price Drop"),
        @Json(name = "Unconfigured") Unconfigured("Unconfigured");
    }

}

