/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FormVersionABTest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param formType The type of form.
 * @param status Status of the form version. \"live\" means it's live on site.
 * @param createdAt ISO8601 timestamp when the form version was created.
 * @param updatedAt ISO8601 timestamp when the form version was last updated.
 * @param abTest 
 */


data class FormVersionResponseObjectResourceAttributes (

    /* The type of form. */
    @Json(name = "form_type")
    val formType: FormVersionResponseObjectResourceAttributes.FormType,

    /* Status of the form version. \"live\" means it's live on site. */
    @Json(name = "status")
    val status: FormVersionResponseObjectResourceAttributes.Status,

    /* ISO8601 timestamp when the form version was created. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* ISO8601 timestamp when the form version was last updated. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "ab_test")
    val abTest: FormVersionABTest? = null

) {

    /**
     * The type of form.
     *
     * Values: banner,embed,flyout,full_page,popup
     */
    @JsonClass(generateAdapter = false)
    enum class FormType(val value: kotlin.String) {
        @Json(name = "banner") banner("banner"),
        @Json(name = "embed") embed("embed"),
        @Json(name = "flyout") flyout("flyout"),
        @Json(name = "full_page") full_page("full_page"),
        @Json(name = "popup") popup("popup");
    }
    /**
     * Status of the form version. \"live\" means it's live on site.
     *
     * Values: draft,live
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "draft") draft("draft"),
        @Json(name = "live") live("live");
    }

}

