/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsFlowAction
import org.openapitools.client.models.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param flowAction 
 * @param template 
 */


data class GetFlowMessageResponseCompoundDocumentDataAllOfRelationships (

    @Json(name = "flow-action")
    val flowAction: GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsFlowAction? = null,

    @Json(name = "template")
    val template: GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate? = null

) {


}

