/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param flow 
 * @param flowMessages 
 */


data class GetFlowActionResponseCollectionDataInnerAllOfRelationships (

    @Json(name = "flow")
    val flow: GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile? = null,

    @Json(name = "flow-messages")
    val flowMessages: GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile? = null

) {


}

