/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationships
import org.openapitools.client.models.GetListRetrieveResponseCompoundDocumentDataAllOfAttributes
import org.openapitools.client.models.ObjectLinks
import org.openapitools.client.models.SegmentEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param id 
 * @param attributes 
 * @param links 
 * @param relationships 
 */


data class GetSegmentRetrieveResponseCompoundDocumentData (

    @Json(name = "type")
    val type: SegmentEnum,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "attributes")
    val attributes: GetListRetrieveResponseCompoundDocumentDataAllOfAttributes,

    @Json(name = "links")
    val links: ObjectLinks,

    @Json(name = "relationships")
    val relationships: GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationships? = null

) {


}

