/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AnyEnum
import org.openapitools.client.models.StatusDateFilter

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subscription 
 * @param filters 
 */


data class HasPushMarketing (

    @Json(name = "subscription")
    val subscription: AnyEnum,

    @Json(name = "filters")
    val filters: kotlin.collections.List<StatusDateFilter>? = null

) {


}

