/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ListEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param `operator` Operators for list length filters.
 * @param `value` 
 */


data class ListLengthFilter (

    @Json(name = "type")
    val type: ListEnum,

    /* Operators for list length filters. */
    @Json(name = "operator")
    val `operator`: ListLengthFilter.`Operator`,

    @Json(name = "value")
    val `value`: kotlin.Int

) {

    /**
     * Operators for list length filters.
     *
     * Values: equals,greaterMinusThan,greaterMinusThanMinusOrMinusEqual,lessMinusThan,lessMinusThanMinusOrMinusEqual
     */
    @JsonClass(generateAdapter = false)
    enum class `Operator`(val value: kotlin.String) {
        @Json(name = "length-equals") equals("length-equals"),
        @Json(name = "length-greater-than") greaterMinusThan("length-greater-than"),
        @Json(name = "length-greater-than-or-equal") greaterMinusThanMinusOrMinusEqual("length-greater-than-or-equal"),
        @Json(name = "length-less-than") lessMinusThan("length-less-than"),
        @Json(name = "length-less-than-or-equal") lessMinusThanMinusOrMinusEqual("length-less-than-or-equal");
    }

}

