/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HasEmailMarketingConsent
import org.openapitools.client.models.HasPushMarketingConsent
import org.openapitools.client.models.HasSMSMarketingConsent
import org.openapitools.client.models.NoEmailMarketingConsent
import org.openapitools.client.models.NoPushMarketing
import org.openapitools.client.models.NoPushMarketingConsent
import org.openapitools.client.models.NoSMSMarketingConsent
import org.openapitools.client.models.PushEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param channel 
 * @param canReceiveMarketing 
 * @param consentStatus 
 */


data class ProfileMarketingConsentConditionConsent (

    @Json(name = "channel")
    val channel: PushEnum,

    @Json(name = "can_receive_marketing")
    val canReceiveMarketing: ProfileMarketingConsentConditionConsent.CanReceiveMarketing,

    @Json(name = "consent_status")
    val consentStatus: NoPushMarketing

) {

    /**
     * 
     *
     * Values: `false`
     */
    @JsonClass(generateAdapter = false)
    enum class CanReceiveMarketing(val value: kotlin.Boolean) {
        @Json(name = "false") `false`("false");
    }

}

