/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProfileMarketingConsentConditionConsent
import org.openapitools.client.models.ProfileMarketingConsentEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param consent 
 */


data class ProfileMarketingConsentCondition (

    @Json(name = "type")
    val type: ProfileMarketingConsentEnum,

    @Json(name = "consent")
    val consent: ProfileMarketingConsentConditionConsent

) {


}

