/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PushProfileUpsertQueryResourceObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The profile associated with the push token to create/update
 *
 * @param `data` 
 */


data class PushTokenCreateQueryResourceObjectAttributesProfile (

    @Json(name = "data")
    val `data`: PushProfileUpsertQueryResourceObject

) {


}

