/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProfileEnum
import org.openapitools.client.models.PushProfileUpsertQueryResourceObjectAttributes

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param attributes 
 * @param id Primary key that uniquely identifies this profile. Generated by Klaviyo.
 */


data class PushProfileUpsertQueryResourceObject (

    @Json(name = "type")
    val type: ProfileEnum,

    @Json(name = "attributes")
    val attributes: PushProfileUpsertQueryResourceObjectAttributes,

    /* Primary key that uniquely identifies this profile. Generated by Klaviyo. */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

