/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProfileSubscriptionBulkCreateJobEnum
import org.openapitools.client.models.SubscriptionCreateJobCreateQueryResourceObjectAttributes
import org.openapitools.client.models.SubscriptionCreateJobCreateQueryResourceObjectRelationships

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param attributes 
 * @param relationships 
 */


data class SubscriptionCreateJobCreateQueryResourceObject (

    @Json(name = "type")
    val type: ProfileSubscriptionBulkCreateJobEnum,

    @Json(name = "attributes")
    val attributes: SubscriptionCreateJobCreateQueryResourceObjectAttributes,

    @Json(name = "relationships")
    val relationships: SubscriptionCreateJobCreateQueryResourceObjectRelationships? = null

) {


}

