/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CatalogItemCreateQueryResourceObjectRelationshipsCategories;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CatalogItemCreateQueryResourceObjectRelationships
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class CatalogItemCreateQueryResourceObjectRelationships {
  @SerializedName("categories")
  private CatalogItemCreateQueryResourceObjectRelationshipsCategories categories = null;

  public CatalogItemCreateQueryResourceObjectRelationships categories(CatalogItemCreateQueryResourceObjectRelationshipsCategories categories) {
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @Schema(description = "")
  public CatalogItemCreateQueryResourceObjectRelationshipsCategories getCategories() {
    return categories;
  }

  public void setCategories(CatalogItemCreateQueryResourceObjectRelationshipsCategories categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogItemCreateQueryResourceObjectRelationships catalogItemCreateQueryResourceObjectRelationships = (CatalogItemCreateQueryResourceObjectRelationships) o;
    return Objects.equals(this.categories, catalogItemCreateQueryResourceObjectRelationships.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogItemCreateQueryResourceObjectRelationships {\n");
    
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
