/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CatalogVariantBulkDeleteJobEnum;
import io.swagger.client.model.CatalogVariantDeleteJobCreateQueryResourceObjectAttributes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CatalogVariantDeleteJobCreateQueryResourceObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class CatalogVariantDeleteJobCreateQueryResourceObject {
  @SerializedName("type")
  private CatalogVariantBulkDeleteJobEnum type = null;

  @SerializedName("attributes")
  private CatalogVariantDeleteJobCreateQueryResourceObjectAttributes attributes = null;

  public CatalogVariantDeleteJobCreateQueryResourceObject type(CatalogVariantBulkDeleteJobEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public CatalogVariantBulkDeleteJobEnum getType() {
    return type;
  }

  public void setType(CatalogVariantBulkDeleteJobEnum type) {
    this.type = type;
  }

  public CatalogVariantDeleteJobCreateQueryResourceObject attributes(CatalogVariantDeleteJobCreateQueryResourceObjectAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(required = true, description = "")
  public CatalogVariantDeleteJobCreateQueryResourceObjectAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(CatalogVariantDeleteJobCreateQueryResourceObjectAttributes attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogVariantDeleteJobCreateQueryResourceObject catalogVariantDeleteJobCreateQueryResourceObject = (CatalogVariantDeleteJobCreateQueryResourceObject) o;
    return Objects.equals(this.type, catalogVariantDeleteJobCreateQueryResourceObject.type) &&
        Objects.equals(this.attributes, catalogVariantDeleteJobCreateQueryResourceObject.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogVariantDeleteJobCreateQueryResourceObject {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
