/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * CouponCodeResponseObjectResourceAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class CouponCodeResponseObjectResourceAttributes {
  @SerializedName("unique_code")
  private String uniqueCode = null;

  @SerializedName("expires_at")
  private OffsetDateTime expiresAt = null;

  /**
   * The current status of the coupon code.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    @SerializedName("ASSIGNED_TO_PROFILE")
    ASSIGNED_TO_PROFILE("ASSIGNED_TO_PROFILE"),
    @SerializedName("DELETING")
    DELETING("DELETING"),
    @SerializedName("PROCESSING")
    PROCESSING("PROCESSING"),
    @SerializedName("UNASSIGNED")
    UNASSIGNED("UNASSIGNED"),
    @SerializedName("USED")
    USED("USED"),
    @SerializedName("VERSION_NOT_ACTIVE")
    VERSION_NOT_ACTIVE("VERSION_NOT_ACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  public CouponCodeResponseObjectResourceAttributes uniqueCode(String uniqueCode) {
    this.uniqueCode = uniqueCode;
    return this;
  }

   /**
   * This is a unique string that will be or is assigned to each customer/profile and is associated with a coupon.
   * @return uniqueCode
  **/
  @Schema(example = "ASD325FHK324UJDOI2M3JNES99", description = "This is a unique string that will be or is assigned to each customer/profile and is associated with a coupon.")
  public String getUniqueCode() {
    return uniqueCode;
  }

  public void setUniqueCode(String uniqueCode) {
    this.uniqueCode = uniqueCode;
  }

  public CouponCodeResponseObjectResourceAttributes expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * The datetime when this coupon code will expire. If not specified or set to null, it will be automatically set to 1 year.
   * @return expiresAt
  **/
  @Schema(example = "2023-01-01T00:00Z", description = "The datetime when this coupon code will expire. If not specified or set to null, it will be automatically set to 1 year.")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  public CouponCodeResponseObjectResourceAttributes status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The current status of the coupon code.
   * @return status
  **/
  @Schema(example = "UNASSIGNED", description = "The current status of the coupon code.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponCodeResponseObjectResourceAttributes couponCodeResponseObjectResourceAttributes = (CouponCodeResponseObjectResourceAttributes) o;
    return Objects.equals(this.uniqueCode, couponCodeResponseObjectResourceAttributes.uniqueCode) &&
        Objects.equals(this.expiresAt, couponCodeResponseObjectResourceAttributes.expiresAt) &&
        Objects.equals(this.status, couponCodeResponseObjectResourceAttributes.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueCode, expiresAt, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponCodeResponseObjectResourceAttributes {\n");
    
    sb.append("    uniqueCode: ").append(toIndentedString(uniqueCode)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
