/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ManualSuppressionDateEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ManualSuppressionDateFilter
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class ManualSuppressionDateFilter implements OneOfNoEmailMarketingFiltersItems, OneOfNoEmailMarketingNeverSubscribedFiltersItems, OneOfNoEmailMarketingSubscribedFiltersItems {
  @SerializedName("field")
  private ManualSuppressionDateEnum field = null;

  @SerializedName("filter")
  private OneOfManualSuppressionDateFilterFilter filter = null;

  public ManualSuppressionDateFilter field(ManualSuppressionDateEnum field) {
    this.field = field;
    return this;
  }

   /**
   * Get field
   * @return field
  **/
  @Schema(required = true, description = "")
  public ManualSuppressionDateEnum getField() {
    return field;
  }

  public void setField(ManualSuppressionDateEnum field) {
    this.field = field;
  }

  public ManualSuppressionDateFilter filter(OneOfManualSuppressionDateFilterFilter filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @Schema(required = true, description = "")
  public OneOfManualSuppressionDateFilterFilter getFilter() {
    return filter;
  }

  public void setFilter(OneOfManualSuppressionDateFilterFilter filter) {
    this.filter = filter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManualSuppressionDateFilter manualSuppressionDateFilter = (ManualSuppressionDateFilter) o;
    return Objects.equals(this.field, manualSuppressionDateFilter.field) &&
        Objects.equals(this.filter, manualSuppressionDateFilter.filter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, filter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManualSuppressionDateFilter {\n");
    
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
