/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CatalogVariantBulkUpdateJobEnum;
import io.swagger.client.model.CouponCodeCreateJobResponseObjectResourceAttributes;
import io.swagger.client.model.ObjectLinks;
import io.swagger.client.model.PostCatalogVariantUpdateJobResponseDataRelationships;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PostCatalogVariantUpdateJobResponseData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class PostCatalogVariantUpdateJobResponseData {
  @SerializedName("type")
  private CatalogVariantBulkUpdateJobEnum type = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("attributes")
  private CouponCodeCreateJobResponseObjectResourceAttributes attributes = null;

  @SerializedName("relationships")
  private PostCatalogVariantUpdateJobResponseDataRelationships relationships = null;

  @SerializedName("links")
  private ObjectLinks links = null;

  public PostCatalogVariantUpdateJobResponseData type(CatalogVariantBulkUpdateJobEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public CatalogVariantBulkUpdateJobEnum getType() {
    return type;
  }

  public void setType(CatalogVariantBulkUpdateJobEnum type) {
    this.type = type;
  }

  public PostCatalogVariantUpdateJobResponseData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for retrieving the job. Generated by Klaviyo.
   * @return id
  **/
  @Schema(required = true, description = "Unique identifier for retrieving the job. Generated by Klaviyo.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PostCatalogVariantUpdateJobResponseData attributes(CouponCodeCreateJobResponseObjectResourceAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(required = true, description = "")
  public CouponCodeCreateJobResponseObjectResourceAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(CouponCodeCreateJobResponseObjectResourceAttributes attributes) {
    this.attributes = attributes;
  }

  public PostCatalogVariantUpdateJobResponseData relationships(PostCatalogVariantUpdateJobResponseDataRelationships relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @Schema(description = "")
  public PostCatalogVariantUpdateJobResponseDataRelationships getRelationships() {
    return relationships;
  }

  public void setRelationships(PostCatalogVariantUpdateJobResponseDataRelationships relationships) {
    this.relationships = relationships;
  }

  public PostCatalogVariantUpdateJobResponseData links(ObjectLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(required = true, description = "")
  public ObjectLinks getLinks() {
    return links;
  }

  public void setLinks(ObjectLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCatalogVariantUpdateJobResponseData postCatalogVariantUpdateJobResponseData = (PostCatalogVariantUpdateJobResponseData) o;
    return Objects.equals(this.type, postCatalogVariantUpdateJobResponseData.type) &&
        Objects.equals(this.id, postCatalogVariantUpdateJobResponseData.id) &&
        Objects.equals(this.attributes, postCatalogVariantUpdateJobResponseData.attributes) &&
        Objects.equals(this.relationships, postCatalogVariantUpdateJobResponseData.relationships) &&
        Objects.equals(this.links, postCatalogVariantUpdateJobResponseData.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, attributes, relationships, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCatalogVariantUpdateJobResponseData {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
