/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProfileLocation;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * ProfileResponseObjectResourceAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class ProfileResponseObjectResourceAttributes {
  @SerializedName("email")
  private String email = null;

  @SerializedName("phone_number")
  private String phoneNumber = null;

  @SerializedName("external_id")
  private String externalId = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  @SerializedName("last_event_date")
  private OffsetDateTime lastEventDate = null;

  @SerializedName("location")
  private ProfileLocation location = null;

  @SerializedName("properties")
  private Object properties = null;

  public ProfileResponseObjectResourceAttributes email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Individual&#x27;s email address
   * @return email
  **/
  @Schema(example = "sarah.mason@klaviyo-demo.com", description = "Individual's email address")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ProfileResponseObjectResourceAttributes phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Individual&#x27;s phone number in E.164 format
   * @return phoneNumber
  **/
  @Schema(example = "+15005550006", description = "Individual's phone number in E.164 format")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public ProfileResponseObjectResourceAttributes externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system. Format varies based on the external system.
   * @return externalId
  **/
  @Schema(description = "A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system. Format varies based on the external system.")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ProfileResponseObjectResourceAttributes firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Individual&#x27;s first name
   * @return firstName
  **/
  @Schema(example = "Sarah", description = "Individual's first name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ProfileResponseObjectResourceAttributes lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Individual&#x27;s last name
   * @return lastName
  **/
  @Schema(example = "Mason", description = "Individual's last name")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ProfileResponseObjectResourceAttributes organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Name of the company or organization within the company for whom the individual works
   * @return organization
  **/
  @Schema(example = "Example Corporation", description = "Name of the company or organization within the company for whom the individual works")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public ProfileResponseObjectResourceAttributes locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * The locale of the profile, in the IETF BCP 47 language tag format (language-extlang-script-region-variant-extension-privateuse)
   * @return locale
  **/
  @Schema(example = "en-US", description = "The locale of the profile, in the IETF BCP 47 language tag format (language-extlang-script-region-variant-extension-privateuse)")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public ProfileResponseObjectResourceAttributes title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Individual&#x27;s job title
   * @return title
  **/
  @Schema(example = "Regional Manager", description = "Individual's job title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ProfileResponseObjectResourceAttributes image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL pointing to the location of a profile image
   * @return image
  **/
  @Schema(example = "https://images.pexels.com/photos/3760854/pexels-photo-3760854.jpeg", description = "URL pointing to the location of a profile image")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public ProfileResponseObjectResourceAttributes created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Date and time when the profile was created, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
   * @return created
  **/
  @Schema(example = "2022-11-08T00:00Z", description = "Date and time when the profile was created, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ProfileResponseObjectResourceAttributes updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Date and time when the profile was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
   * @return updated
  **/
  @Schema(example = "2022-11-08T00:00Z", description = "Date and time when the profile was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }

  public ProfileResponseObjectResourceAttributes lastEventDate(OffsetDateTime lastEventDate) {
    this.lastEventDate = lastEventDate;
    return this;
  }

   /**
   * Date and time of the most recent event the triggered an update to the profile, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
   * @return lastEventDate
  **/
  @Schema(example = "2022-11-08T00:00Z", description = "Date and time of the most recent event the triggered an update to the profile, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)")
  public OffsetDateTime getLastEventDate() {
    return lastEventDate;
  }

  public void setLastEventDate(OffsetDateTime lastEventDate) {
    this.lastEventDate = lastEventDate;
  }

  public ProfileResponseObjectResourceAttributes location(ProfileLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public ProfileLocation getLocation() {
    return location;
  }

  public void setLocation(ProfileLocation location) {
    this.location = location;
  }

  public ProfileResponseObjectResourceAttributes properties(Object properties) {
    this.properties = properties;
    return this;
  }

   /**
   * An object containing key/value pairs for any custom properties assigned to this profile
   * @return properties
  **/
  @Schema(example = "{\"pseudonym\":\"Dr. Octopus\"}", description = "An object containing key/value pairs for any custom properties assigned to this profile")
  public Object getProperties() {
    return properties;
  }

  public void setProperties(Object properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileResponseObjectResourceAttributes profileResponseObjectResourceAttributes = (ProfileResponseObjectResourceAttributes) o;
    return Objects.equals(this.email, profileResponseObjectResourceAttributes.email) &&
        Objects.equals(this.phoneNumber, profileResponseObjectResourceAttributes.phoneNumber) &&
        Objects.equals(this.externalId, profileResponseObjectResourceAttributes.externalId) &&
        Objects.equals(this.firstName, profileResponseObjectResourceAttributes.firstName) &&
        Objects.equals(this.lastName, profileResponseObjectResourceAttributes.lastName) &&
        Objects.equals(this.organization, profileResponseObjectResourceAttributes.organization) &&
        Objects.equals(this.locale, profileResponseObjectResourceAttributes.locale) &&
        Objects.equals(this.title, profileResponseObjectResourceAttributes.title) &&
        Objects.equals(this.image, profileResponseObjectResourceAttributes.image) &&
        Objects.equals(this.created, profileResponseObjectResourceAttributes.created) &&
        Objects.equals(this.updated, profileResponseObjectResourceAttributes.updated) &&
        Objects.equals(this.lastEventDate, profileResponseObjectResourceAttributes.lastEventDate) &&
        Objects.equals(this.location, profileResponseObjectResourceAttributes.location) &&
        Objects.equals(this.properties, profileResponseObjectResourceAttributes.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, phoneNumber, externalId, firstName, lastName, organization, locale, title, image, created, updated, lastEventDate, location, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileResponseObjectResourceAttributes {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    lastEventDate: ").append(toIndentedString(lastEventDate)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
