/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SendOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class SendOptions {
  @SerializedName("use_smart_sending")
  private Boolean useSmartSending = null;

  @SerializedName("is_transactional")
  private Boolean isTransactional = null;

  public SendOptions useSmartSending(Boolean useSmartSending) {
    this.useSmartSending = useSmartSending;
    return this;
  }

   /**
   * Get useSmartSending
   * @return useSmartSending
  **/
  @Schema(required = true, description = "")
  public Boolean isUseSmartSending() {
    return useSmartSending;
  }

  public void setUseSmartSending(Boolean useSmartSending) {
    this.useSmartSending = useSmartSending;
  }

  public SendOptions isTransactional(Boolean isTransactional) {
    this.isTransactional = isTransactional;
    return this;
  }

   /**
   * Get isTransactional
   * @return isTransactional
  **/
  @Schema(required = true, description = "")
  public Boolean isIsTransactional() {
    return isTransactional;
  }

  public void setIsTransactional(Boolean isTransactional) {
    this.isTransactional = isTransactional;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendOptions sendOptions = (SendOptions) o;
    return Objects.equals(this.useSmartSending, sendOptions.useSmartSending) &&
        Objects.equals(this.isTransactional, sendOptions.isTransactional);
  }

  @Override
  public int hashCode() {
    return Objects.hash(useSmartSending, isTransactional);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendOptions {\n");
    
    sb.append("    useSmartSending: ").append(toIndentedString(useSmartSending)).append("\n");
    sb.append("    isTransactional: ").append(toIndentedString(isTransactional)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
