/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TemplateUpdateQueryResourceObjectAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T16:09:09.130713678Z[GMT]")

public class TemplateUpdateQueryResourceObjectAttributes {
  @SerializedName("name")
  private String name = null;

  @SerializedName("html")
  private String html = null;

  @SerializedName("text")
  private String text = null;

  public TemplateUpdateQueryResourceObjectAttributes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the template
   * @return name
  **/
  @Schema(example = "Monthly Newsletter Template", description = "The name of the template")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TemplateUpdateQueryResourceObjectAttributes html(String html) {
    this.html = html;
    return this;
  }

   /**
   * The HTML of the template
   * @return html
  **/
  @Schema(example = "               <html>                   <body>                       hello world                   </body>               </html>           ", description = "The HTML of the template")
  public String getHtml() {
    return html;
  }

  public void setHtml(String html) {
    this.html = html;
  }

  public TemplateUpdateQueryResourceObjectAttributes text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The plaintext of the template
   * @return text
  **/
  @Schema(example = "hello world", description = "The plaintext of the template")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateUpdateQueryResourceObjectAttributes templateUpdateQueryResourceObjectAttributes = (TemplateUpdateQueryResourceObjectAttributes) o;
    return Objects.equals(this.name, templateUpdateQueryResourceObjectAttributes.name) &&
        Objects.equals(this.html, templateUpdateQueryResourceObjectAttributes.html) &&
        Objects.equals(this.text, templateUpdateQueryResourceObjectAttributes.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, html, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateUpdateQueryResourceObjectAttributes {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
