/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CouponCodeCreateJobCreateQuery;
import io.swagger.client.model.CouponCodeCreateQuery;
import io.swagger.client.model.CouponCodeUpdateQuery;
import io.swagger.client.model.CouponCreateQuery;
import io.swagger.client.model.CouponUpdateQuery;
import io.swagger.client.model.GetCouponCodeCreateJobResponseCollectionCompoundDocument;
import io.swagger.client.model.GetCouponCodeCreateJobResponseCompoundDocument;
import io.swagger.client.model.GetCouponCodeRelationshipCouponResponse;
import io.swagger.client.model.GetCouponCodeResponseCollection;
import io.swagger.client.model.GetCouponCodeResponseCollectionCompoundDocument;
import io.swagger.client.model.GetCouponCodeResponseCompoundDocument;
import io.swagger.client.model.GetCouponRelationshipCouponCodesListResponseCollection;
import io.swagger.client.model.GetCouponResponse;
import io.swagger.client.model.GetCouponResponseCollection;
import io.swagger.client.model.InlineResponse4XX;
import io.swagger.client.model.PatchCouponCodeResponse;
import io.swagger.client.model.PatchCouponResponse;
import io.swagger.client.model.PostCouponCodeCreateJobResponse;
import io.swagger.client.model.PostCouponCodeResponse;
import io.swagger.client.model.PostCouponResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CouponsApi
 */
@Ignore
public class CouponsApiTest {

    private final CouponsApi api = new CouponsApi();

    /**
     * Create Coupon
     *
     * Creates a new coupon.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;3/s&#x60;&lt;br&gt;Steady: &#x60;60/m&#x60;  **Scopes:** &#x60;coupons:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCouponTest() throws Exception {
        CouponCreateQuery body = null;
        String revision = null;
        PostCouponResponse response = api.createCoupon(body, revision);

        // TODO: test validations
    }
    /**
     * Create Coupon Code
     *
     * Synchronously creates a coupon code for the given coupon.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;350/s&#x60;&lt;br&gt;Steady: &#x60;3500/m&#x60;  **Scopes:** &#x60;coupon-codes:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCouponCodeTest() throws Exception {
        CouponCodeCreateQuery body = null;
        String revision = null;
        PostCouponCodeResponse response = api.createCouponCode(body, revision);

        // TODO: test validations
    }
    /**
     * Delete Coupon
     *
     * Delete the coupon with the given coupon ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;3/s&#x60;&lt;br&gt;Steady: &#x60;60/m&#x60;  **Scopes:** &#x60;coupons:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCouponTest() throws Exception {
        String id = null;
        String revision = null;
        api.deleteCoupon(id, revision);

        // TODO: test validations
    }
    /**
     * Delete Coupon Code
     *
     * Deletes a coupon code specified by the given identifier synchronously. If a profile has been assigned to the coupon code, an exception will be raised&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;350/s&#x60;&lt;br&gt;Steady: &#x60;3500/m&#x60;  **Scopes:** &#x60;coupon-codes:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCouponCodeTest() throws Exception {
        String id = null;
        String revision = null;
        api.deleteCouponCode(id, revision);

        // TODO: test validations
    }
    /**
     * Get Coupon
     *
     * Get a specific coupon with the given coupon ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupons:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponTest() throws Exception {
        String id = null;
        String revision = null;
        List<String> fieldsCoupon = null;
        GetCouponResponse response = api.getCoupon(id, revision, fieldsCoupon);

        // TODO: test validations
    }
    /**
     * Get Coupon Code
     *
     * Returns a Coupon Code specified by the given identifier.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;350/s&#x60;&lt;br&gt;Steady: &#x60;3500/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodeTest() throws Exception {
        String id = null;
        String revision = null;
        List<String> fieldsCouponCode = null;
        List<String> fieldsCoupon = null;
        List<String> include = null;
        GetCouponCodeResponseCompoundDocument response = api.getCouponCode(id, revision, fieldsCouponCode, fieldsCoupon, include);

        // TODO: test validations
    }
    /**
     * Get Coupon Code Bulk Create Job
     *
     * Get a coupon code bulk create job with the given job ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodeBulkCreateJobTest() throws Exception {
        String jobId = null;
        String revision = null;
        List<String> fieldsCouponCodeBulkCreateJob = null;
        List<String> fieldsCouponCode = null;
        List<String> include = null;
        GetCouponCodeCreateJobResponseCompoundDocument response = api.getCouponCodeBulkCreateJob(jobId, revision, fieldsCouponCodeBulkCreateJob, fieldsCouponCode, include);

        // TODO: test validations
    }
    /**
     * Get Coupon Code Bulk Create Jobs
     *
     * Get all coupon code bulk create jobs.  Returns a maximum of 100 jobs per request.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodeBulkCreateJobsTest() throws Exception {
        String revision = null;
        List<String> fieldsCouponCodeBulkCreateJob = null;
        String filter = null;
        String pageCursor = null;
        GetCouponCodeCreateJobResponseCollectionCompoundDocument response = api.getCouponCodeBulkCreateJobs(revision, fieldsCouponCodeBulkCreateJob, filter, pageCursor);

        // TODO: test validations
    }
    /**
     * Get Coupon Code Relationships Coupon
     *
     * Gets a list of coupon code relationships associated with the given coupon id&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodeRelationshipsCouponTest() throws Exception {
        String id = null;
        String revision = null;
        String pageCursor = null;
        GetCouponRelationshipCouponCodesListResponseCollection response = api.getCouponCodeRelationshipsCoupon(id, revision, pageCursor);

        // TODO: test validations
    }
    /**
     * Get Coupon Codes
     *
     * Gets a list of coupon codes associated with a coupon/coupons or a profile/profiles.  A coupon/coupons or a profile/profiles must be provided as required filter params.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;350/s&#x60;&lt;br&gt;Steady: &#x60;3500/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodesTest() throws Exception {
        String revision = null;
        List<String> fieldsCouponCode = null;
        List<String> fieldsCoupon = null;
        String filter = null;
        List<String> include = null;
        String pageCursor = null;
        GetCouponCodeResponseCollectionCompoundDocument response = api.getCouponCodes(revision, fieldsCouponCode, fieldsCoupon, filter, include, pageCursor);

        // TODO: test validations
    }
    /**
     * Get Coupon Codes For Coupon
     *
     * Gets a list of coupon codes associated with the given coupon id&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupon-codes:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponCodesForCouponTest() throws Exception {
        String id = null;
        String revision = null;
        List<String> fieldsCouponCode = null;
        String filter = null;
        String pageCursor = null;
        GetCouponCodeResponseCollection response = api.getCouponCodesForCoupon(id, revision, fieldsCouponCode, filter, pageCursor);

        // TODO: test validations
    }
    /**
     * Get Coupon For Coupon Code
     *
     * Get the coupon associated with a given coupon code ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupons:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponForCouponCodeTest() throws Exception {
        String id = null;
        String revision = null;
        List<String> fieldsCoupon = null;
        GetCouponResponseCollection response = api.getCouponForCouponCode(id, revision, fieldsCoupon);

        // TODO: test validations
    }
    /**
     * Get Coupon Relationships Coupon Codes
     *
     * Gets the coupon relationship associated with the given coupon code id&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupons:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponRelationshipsCouponCodesTest() throws Exception {
        String id = null;
        String revision = null;
        GetCouponCodeRelationshipCouponResponse response = api.getCouponRelationshipsCouponCodes(id, revision);

        // TODO: test validations
    }
    /**
     * Get Coupons
     *
     * Get all coupons in an account.  To learn more, see our [Coupons API guide](https://developers.klaviyo.com/en/docs/use_klaviyos_coupons_api).&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupons:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCouponsTest() throws Exception {
        String revision = null;
        List<String> fieldsCoupon = null;
        String pageCursor = null;
        GetCouponResponseCollection response = api.getCoupons(revision, fieldsCoupon, pageCursor);

        // TODO: test validations
    }
    /**
     * Spawn Coupon Code Bulk Create Job
     *
     * Create a coupon-code-bulk-create-job to bulk create a list of coupon codes.  Max number of coupon codes per job we allow for is 1000. Max number of jobs queued at once we allow for is 100.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;75/s&#x60;&lt;br&gt;Steady: &#x60;700/m&#x60;  **Scopes:** &#x60;coupon-codes:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void spawnCouponCodeBulkCreateJobTest() throws Exception {
        CouponCodeCreateJobCreateQuery body = null;
        String revision = null;
        PostCouponCodeCreateJobResponse response = api.spawnCouponCodeBulkCreateJob(body, revision);

        // TODO: test validations
    }
    /**
     * Update Coupon
     *
     * *Rate limits*:&lt;br&gt;Burst: &#x60;3/s&#x60;&lt;br&gt;Steady: &#x60;60/m&#x60;  **Scopes:** &#x60;coupons:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCouponTest() throws Exception {
        CouponUpdateQuery body = null;
        String revision = null;
        String id = null;
        PatchCouponResponse response = api.updateCoupon(body, revision, id);

        // TODO: test validations
    }
    /**
     * Update Coupon Code
     *
     * Updates a coupon code specified by the given identifier synchronously. We allow updating the &#x27;status&#x27; and &#x27;expires_at&#x27; of coupon codes.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;350/s&#x60;&lt;br&gt;Steady: &#x60;3500/m&#x60;  **Scopes:** &#x60;coupon-codes:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCouponCodeTest() throws Exception {
        CouponCodeUpdateQuery body = null;
        String revision = null;
        String id = null;
        PatchCouponCodeResponse response = api.updateCouponCode(body, revision, id);

        // TODO: test validations
    }
}
