/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CampaignValuesRequestDTO;
import io.swagger.client.model.FlowSeriesRequestDTO;
import io.swagger.client.model.FlowValuesRequestDTO;
import io.swagger.client.model.InlineResponse4XX;
import io.swagger.client.model.PostCampaignValuesResponseDTO;
import io.swagger.client.model.PostFlowSeriesResponseDTO;
import io.swagger.client.model.PostFlowValuesResponseDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ReportingApi
 */
@Ignore
public class ReportingApiTest {

    private final ReportingApi api = new ReportingApi();

    /**
     * Query Campaign Values
     *
     * Returns the requested campaign analytics values data&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;2/m&#x60;&lt;br&gt;Daily: &#x60;225/d&#x60;  **Scopes:** &#x60;campaigns:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryCampaignValuesTest() throws Exception {
        CampaignValuesRequestDTO body = null;
        String revision = null;
        String pageCursor = null;
        PostCampaignValuesResponseDTO response = api.queryCampaignValues(body, revision, pageCursor);

        // TODO: test validations
    }
    /**
     * Query Flow Series
     *
     * Returns the requested flow analytics series data&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;2/m&#x60;&lt;br&gt;Daily: &#x60;225/d&#x60;  **Scopes:** &#x60;flows:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryFlowSeriesTest() throws Exception {
        FlowSeriesRequestDTO body = null;
        String revision = null;
        String pageCursor = null;
        PostFlowSeriesResponseDTO response = api.queryFlowSeries(body, revision, pageCursor);

        // TODO: test validations
    }
    /**
     * Query Flow Values
     *
     * Returns the requested flow analytics values data&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;2/m&#x60;&lt;br&gt;Daily: &#x60;225/d&#x60;  **Scopes:** &#x60;flows:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void queryFlowValuesTest() throws Exception {
        FlowValuesRequestDTO body = null;
        String revision = null;
        String pageCursor = null;
        PostFlowValuesResponseDTO response = api.queryFlowValues(body, revision, pageCursor);

        // TODO: test validations
    }
}
