/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.GetWebhookResponseCollectionCompoundDocument;
import io.swagger.client.model.GetWebhookResponseCompoundDocument;
import io.swagger.client.model.GetWebhookTopicResponse;
import io.swagger.client.model.GetWebhookTopicResponseCollection;
import io.swagger.client.model.InlineResponse4XX;
import io.swagger.client.model.PatchWebhookResponse;
import io.swagger.client.model.PostWebhookResponse;
import io.swagger.client.model.WebhookCreateQuery;
import io.swagger.client.model.WebhookPartialUpdateQuery;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    /**
     * Create Webhook
     *
     * Create a new Webhook&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createWebhookTest() throws Exception {
        WebhookCreateQuery body = null;
        String revision = null;
        PostWebhookResponse response = api.createWebhook(body, revision);

        // TODO: test validations
    }
    /**
     * Delete Webhook
     *
     * Delete a webhook with the given ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteWebhookTest() throws Exception {
        String id = null;
        String revision = null;
        api.deleteWebhook(id, revision);

        // TODO: test validations
    }
    /**
     * Get Webhook
     *
     * Get the webhook with the given ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWebhookTest() throws Exception {
        String id = null;
        String revision = null;
        List<String> fieldsWebhook = null;
        List<String> include = null;
        GetWebhookResponseCompoundDocument response = api.getWebhook(id, revision, fieldsWebhook, include);

        // TODO: test validations
    }
    /**
     * Get Webhook Topic
     *
     * Get the webhook topic with the given ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWebhookTopicTest() throws Exception {
        String id = null;
        String revision = null;
        GetWebhookTopicResponse response = api.getWebhookTopic(id, revision);

        // TODO: test validations
    }
    /**
     * Get Webhook Topics
     *
     * Get all webhook topics in a Klaviyo account.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWebhookTopicsTest() throws Exception {
        String revision = null;
        GetWebhookTopicResponseCollection response = api.getWebhookTopics(revision);

        // TODO: test validations
    }
    /**
     * Get Webhooks
     *
     * Get all webhooks in an account.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:read&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWebhooksTest() throws Exception {
        String revision = null;
        List<String> fieldsWebhook = null;
        List<String> include = null;
        GetWebhookResponseCollectionCompoundDocument response = api.getWebhooks(revision, fieldsWebhook, include);

        // TODO: test validations
    }
    /**
     * Update Webhook
     *
     * Update the webhook with the given ID.&lt;br&gt;&lt;br&gt;*Rate limits*:&lt;br&gt;Burst: &#x60;1/s&#x60;&lt;br&gt;Steady: &#x60;15/m&#x60;  **Scopes:** &#x60;webhooks:write&#x60;
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateWebhookTest() throws Exception {
        WebhookPartialUpdateQuery body = null;
        String revision = null;
        String id = null;
        PatchWebhookResponse response = api.updateWebhook(body, revision, id);

        // TODO: test validations
    }
}
